apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: botkube-role
  namespace: default
rules:
  - apiGroups: ["apps"]
    resources: ["deployments"]
    verbs: ["get", "list", "watch", "update", "patch"]


---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: botkube-rolebinding
  namespace: default
subjects:
  - kind: ServiceAccount
    name: botkube
    namespace: botkube  # Botkube's namespace
roleRef:
  kind: Role
  name: botkube-role
  apiGroup: rbac.authorization.k8s.io
