name: Deploy JavaScript App to Kubernetes
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install kubectl
        uses: azure/setup-kubectl@v3
        
      - name: Setup kube config
        run: |
          # Create kubeconfig directory
          mkdir -p $HOME/.kube
          
          # Create kubeconfig file with token authentication
          cat << EOF > $HOME/.kube/config
          apiVersion: v1
          kind: Config
          clusters:
          - cluster:
              server: https://${{ secrets.NGROK_URL }}
              insecure-skip-tls-verify: true
            name: docker-desktop
          contexts:
          - context:
              cluster: docker-desktop
              namespace: bassa
              user: bassa-user
            name: bassa-context
          current-context: bassa-context
          users:
          - name: bassa-user
            user:
              token: ${{ secrets.BASSA_TOKEN }}
          EOF
          
          # Set proper permissions
          chmod 600 $HOME/.kube/config
          
          # Verify configuration
          kubectl config view
          kubectl config current-context

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: metehan1171/devops-case:latest

      - name: Verify Kubernetes Connection
        run: |
          echo "Checking cluster access..."
          kubectl get nodes
          echo "Checking namespace access..."
          kubectl get namespace bassa
          echo "Checking pod access..."
          kubectl get pods -n bassa

      - name: Deploy to Kubernetes
        run: |
          kubectl apply -f ./kubernetes/deployment.yaml -n bassa
          kubectl apply -f ./kubernetes/ingress.yaml -n bassa
          
          # Verify deployment
          echo "Checking deployment status..."
          kubectl get deployments -n bassa
          kubectl get pods -n bassa