name: Deploy JavaScript App to Kubernetes
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install kubectl
        uses: azure/setup-kubectl@v3
        
      - name: Create and validate kubeconfig
        run: |
          mkdir -p $HOME/.kube
          # First echo the secret to a temporary file for inspection
          echo "${{ secrets.KUBE_CONFIG }}" > /tmp/kube_tmp
          
          # Check if the content is base64 encoded and decode if necessary
          if [[ $(cat /tmp/kube_tmp | head -1 | base64 -d 2>/dev/null | grep -E '^apiVersion|^kind' > /dev/null; echo $?) -eq 0 ]]; then
            echo "${{ secrets.KUBE_CONFIG }}" | base64 -d > $HOME/.kube/config
          else
            echo "${{ secrets.KUBE_CONFIG }}" > $HOME/.kube/config
          fi
          
          # Verify the file is valid YAML
          chmod 600 $HOME/.kube/config
          
          # Debug: Show file structure (without sensitive data)
          echo "Kubeconfig structure:"
          grep -E '^apiVersion|^kind|^clusters:|^contexts:|^users:' $HOME/.kube/config || true

      - name: Setup cluster configuration
        run: |
          # Create a basic kubeconfig if it doesn't exist
          if ! kubectl config view &>/dev/null; then
            kubectl config set-cluster docker-desktop \
              --server=https://${{ secrets.NGROK_URL }} \
              --insecure-skip-tls-verify=true
          fi
          
          # Update the server URL
          kubectl config set-cluster docker-desktop \
            --server=https://${{ secrets.NGROK_URL }} \
            --insecure-skip-tls-verify=true
          
          kubectl config use-context docker-desktop || {
            echo "Failed to set context. Available contexts:"
            kubectl config get-contexts
          }

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: metehan1171/devops-case:latest

      - name: Deploy to Kubernetes
        run: |
          kubectl apply -f kubernetes/deployment.yaml
          kubectl apply -f kubernetes/ingress.yaml