name: Deploy JavaScript App to Kubernetes
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install kubectl
        uses: azure/setup-kubectl@v3
        
      - name: Setup kube config
        run: |
          mkdir -p $HOME/.kube
          # Explicitly decode base64 kubeconfig
          echo "${{ secrets.KUBE_CONFIG }}" | base64 -d > $HOME/.kube/config
          chmod 600 $HOME/.kube/config
          
          # Update the server URL while keeping credentials
          kubectl config set-cluster $(kubectl config current-context) \
            --server=https://${{ secrets.NGROK_URL }} \
            --insecure-skip-tls-verify=true

      - name: Verify kubectl configuration
        run: |
          echo "Verifying cluster connection..."
          kubectl cluster-info
          echo "Current context:"
          kubectl config current-context

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: metehan1171/devops-case:latest

      - name: Deploy to Kubernetes
        run: |
          kubectl apply -f kubernetes/deployment.yaml
          kubectl apply -f kubernetes/ingress.yaml