name: Deploy JavaScript App to Kubernetes

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install kubectl
        uses: azure/setup-kubectl@v3
        
      - name: Create kubeconfig
        run: |
          mkdir -p $HOME/.kube
          echo "${{ secrets.KUBE_CONFIG }}" > $HOME/.kube/config
          chmod 600 $HOME/.kube/config

      - name: Configure kubectl for ngrok
        run: |
          kubectl config set-cluster docker-desktop \
            --server=https://${{ secrets.NGROK_URL }} \
            --insecure-skip-tls-verify=true \
            --kubeconfig=$HOME/.kube/config
          
          kubectl config use-context docker-desktop --kubeconfig=$HOME/.kube/config

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: metehan1171/devops-case:latest

      - name: Deploy to Kubernetes
        run: |
          kubectl apply -f kubernetes/deployment.yaml --kubeconfig=$HOME/.kube/config
          kubectl apply -f kubernetes/ingress.yaml --kubeconfig=$HOME/.kube/config