name: Build and Deploy Application
on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image with PR commit SHA
        run: docker build -t metehan1171/devops-case:${{ github.sha }} .

      - name: Push Docker image with PR commit SHA
        run: docker push metehan1171/devops-case:${{ github.sha }}

      - name: Notify Slack
        run: |
          curl -X POST -H 'Content-type: application/json' \
          --data '{"text": "🚀 New image built and pushed: metehan1171/devops-case:${{ github.sha }}"}' \
          ${{ secrets.SLACK_WEBHOOK_URL }}
